// This file is generated by Slice Machine. Update with care!

import BooN from './BooN';
import TextImage from './TextImage';

export {
	BooN,
	TextImage,
};

export const components = {
	boo_n: BooN,
	text_image: TextImage,
};
