// import InitialSection from "../InitialSection";
import AfterMarsColonization from "../AfterMarsCollonization";
import MindMap from "../MindMap";
// import RoundEarth from "../RoundEarth";
// import dynamic from "next/dynamic";
import styles from "./MainLayout.module.scss";
import Head from "next/head";
import Three from "../Three";

// const MintContainer = dynamic(() => import("../MintContainer"), {
//   ssr: false
// });
// const RoundEarth = dynamic(() => import("../RoundPlanets"), {
//   ssr: false
// });

const MainLayout = () => {
  return (
    <main className={styles.main}>
      <Head>
        <title>Planet 61</title>
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <meta name="description" content="Generated by Planet61 team" />
      </Head>
      {/* <MintContainer /> */}
      {/* <InitialSection /> */}
      <Three />
      <AfterMarsColonization />
      <MindMap />
    </main>
  );
};
export default MainLayout;
