import AfterMarsColonization from "../AfterMarsCollonization";
import MindMap from "../MindMap";
// import GalaxyscreenInfo from "../common/GalaxyScreenInfo";
// import RoundEarth from "../RoundEarth";
// import dynamic from "next/dynamic";
import styles from "./MainLayout.module.scss";
import Head from "next/head";
// import GalaxyScreen from "../GalaxyScreen";
import Roadmap from "../RoadMap";

import QuestionSection from "../QuestionSection";
import Footer from "../Footer";
import HeaderComponent from "../common/Header";
// import dynamic from "next/dynamic";
import Script from "next/script";
import { useWebViewDetector } from "../../hooks/useWebViewDetector";
import { useEffect, useState } from "react";
import { RedirectModal } from "../RedirectPoopup";

// const MintContainer = dynamic(() => import("../MintContainer"), {
//   ssr: false
// });

// const MintContainer = dynamic(() => import("../common/MintContainer"), {
//   ssr: false
// });
// const RoundEarth = dynamic(() => import("../RoundPlanets"), {
//   ssr: false
// });
const GA_MEASUREMENT_ID = "G-R6GH2KD393";

const MainLayout = () => {
  const { isWebView, userAgent } = useWebViewDetector();
  const [openRedirectPopup, setOpenRedirectPopup] = useState(false);

  useEffect(() => {
    if (isWebView) {
      setOpenRedirectPopup(true);
    }
  }, [isWebView]);

  return (
    <main className={styles.main}>
      <Head>
        <title>Planet 61</title>
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <meta name="description" content="Generated by Planet61 team" />
      </Head>
      <Script
        src={`https://www.googletagmanager.com/gtag/js?id=${GA_MEASUREMENT_ID}`}
        strategy="afterInteractive"
      />
      <Script id="google-analytics" strategy="afterInteractive">
        {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){window.dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', '${GA_MEASUREMENT_ID}');
        `}
      </Script>
      <HeaderComponent />
      {openRedirectPopup && (
        <RedirectModal onClose={() => setOpenRedirectPopup(false)} />
      )}
      {/* <GalaxyScreen
        render={() => (
          <>
            <GalaxyscreenInfo />
            <MintContainer />
          </>
        )}
      /> */}
      <div
        style={{
          position: "absolute",
          top: 0,
          left: 0,
          background: "white",
          color: "#000",
          zIndex: 100000
        }}
      >
        {userAgent?.toString()}
      </div>
      {/* <RoundEarth/> */}
      <AfterMarsColonization />
      <MindMap />
      <Roadmap />
      <QuestionSection />
      <Footer />
    </main>
  );
};
export default MainLayout;
