import Header from "../common/Header";
import InitialSection from "../InitialSection";
import AfterMarsCallonisation from "../AfterMarsCallonisation";
import DamnWenches from "../DamnWenches";
import styles from "./MainLayout.module.scss";
import Head from "next/head";

const MainLayout = () => {
  return (
    <main className={styles.main}>
      <Head>
        <title>Planet 61</title>
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <meta name="description" content="Generated by Planet61 team" />
      </Head>
      <Header />
      <InitialSection />
      <AfterMarsCallonisation />
      <DamnWenches />
    </main>
  );
};
export default MainLayout;
