

# name: Deploy Now

# on:
#   - push
#   - workflow_dispatch

# jobs:
#   deploy-now:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Fetch project data
#         uses: ionos-deploy-now/retrieve-project-info-action@v1
#         id: project
#         with:
#           api-key: ${{ secrets.IONOS_API_KEY }}
#           project: ${{ secrets.IONOS_PROJECT_ID }}
#           service-host: api-eu.ionos.space

#       - name: checkout
#         if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
#         uses: actions/checkout@v2
#         with:
#           submodules: 'recursive'

#       - name: Setup Node
#         if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: v14.x

#       - name: Build Node assets
#         env:
#           CI: true
#           SITE_URL: ${{ steps.project.outputs.site-url }}
#         run: |
#           npm ci

#       - name: Deploy to IONOS
#         if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
#         uses: ionos-deploy-now/deploy-to-ionos-action@v1
#         with:
#           project: ${{ secrets.IONOS_PROJECT_ID }}
#           branch-id: ${{ steps.project.outputs.branch-id }}
#           service-host: api-eu.ionos.space
#           api-key: ${{ secrets.IONOS_API_KEY }}
#           dist-folder: ./out

name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
